from .SportSchema import *
from .BadmintonSportSchema import *
from .VolleyballSportSchema import *
from .CurlingSportSchema  import *
from .GolfSportSchema   import *
from .CyclingTrackSportSchema import *
from .SwimmingSportSchema import *
from .HockeySportSchema import *
from .IceHockeySportSchema import *
from .RugbySportSchema import *
from .GymnasticRhythmicSportSchema import *
from .FencingSportSchema import *
from .FieldHockeySportSchema import *
from .BoxingSportSchema import *
from .ShootingSportSchema import *
from .SailingSportSchema import *
from .SoftballSportSchema import *
from .WrestlingSportSchema import *
from .CrossCountrySportSchema import *
from .ESPNFanSchema import *